export const CountryList = [
    { code: 'AFG', label: 'Afghanistan' },
    { code: 'ALB', label: 'Albania' },
    { code: 'DZA', label: 'Algeria' },
    { code: 'AND', label: 'Andorra' },
    { code: 'AGO', label: 'Angola' },
    { code: 'AIA', label: 'Anguilla' },
    { code: 'ATA', label: 'Antarctica' },
    { code: 'ATG', label: 'Antigua and Barbuda' },
    { code: 'ARG', label: 'Argentina' },
    { code: 'ARM', label: 'Armenia' },
    { code: 'ABW', label: 'Aruba' },
    { code: 'AUS', label: 'Australia' },
    { code: 'AUT', label: 'Austria' },
    { code: 'AZE', label: 'Azerbaijan' },
    { code: 'BHS', label: 'Bahamas' },
    { code: 'BHR', label: 'Bahrain' },
    { code: 'BGD', label: 'Bangladesh' },
    { code: 'BRB', label: 'Barbados' },
    { code: 'BLR', label: 'Belarus' },
    { code: 'BEL', label: 'Belgium' },
    { code: 'BLZ', label: 'Belize' },
    { code: 'BEN', label: 'Benin' },
    { code: 'BMU', label: 'Bermuda' },
    { code: 'BTN', label: 'Bhutan' },
    { code: 'BOL', label: 'Bolivia' },
    { code: 'BIH', label: 'Bosnia and Herzegovina' },
    { code: 'BWA', label: 'Botswana' },
    { code: 'BRA', label: 'Brazil' },
    { code: 'VGB', label: 'British Virgin Islands' },
    { code: 'BRN', label: 'Brunei' },
    { code: 'BGR', label: 'Bulgaria' },
    { code: 'BFA', label: 'Burkina Faso' },
    { code: 'BDI', label: 'Burundi' },
    { code: 'KHM', label: 'Cambodia' },
    { code: 'CMR', label: 'Cameroon' },
    { code: 'CAN', label: 'Canada' },
    { code: 'CPV', label: 'Cape Verde' },
    { code: 'CYM', label: 'Cayman Islands' },
    { code: 'CAF', label: 'Central African Republic' },
    { code: 'TCD', label: 'Chad' },
    { code: 'CHL', label: 'Chile' },
    { code: 'CHN', label: 'China' },
    { code: 'COL', label: 'Colombia' },
    { code: 'COM', label: 'Comoros' },
    { code: 'COG', label: 'Congo' },
    { code: 'COD', label: 'Congo, Democratic Republic of the' },
    { code: 'COK', label: 'Cook Islands' },
    { code: 'CRI', label: 'Costa Rica' },
    { code: 'CIV', label: "Côte d'Ivoire" },
    { code: 'HRV', label: 'Croatia' },
    { code: 'CUB', label: 'Cuba' },
    { code: 'CUW', label: 'Curaçao' },
    { code: 'CYP', label: 'Cyprus' },
    { code: 'CZE', label: 'Czech Republic' },
    { code: 'DNK', label: 'Denmark' },
    { code: 'DJI', label: 'Djibouti' },
    { code: 'DMA', label: 'Dominica' },
    { code: 'DOM', label: 'Dominican Republic' },
    { code: 'ECU', label: 'Ecuador' },
    { code: 'EGY', label: 'Egypt' },
    { code: 'SLV', label: 'El Salvador' },
    { code: 'GNQ', label: 'Equatorial Guinea' },
    { code: 'ERI', label: 'Eritrea' },
    { code: 'EST', label: 'Estonia' },
    { code: 'ETH', label: 'Ethiopia' },
    { code: 'FLK', label: 'Falkland Islands' },
    { code: 'FRO', label: 'Faroe Islands' },
    { code: 'FJI', label: 'Fiji' },
    { code: 'FIN', label: 'Finland' },
    { code: 'FRA', label: 'France' },
    { code: 'GUF', label: 'French Guiana' },
    { code: 'PYF', label: 'French Polynesia' },
    { code: 'GAB', label: 'Gabon' },
    { code: 'GMB', label: 'Gambia' },
    { code: 'GEO', label: 'Georgia' },
    { code: 'DEU', label: 'Germany' },
    { code: 'GHA', label: 'Ghana' },
    { code: 'GIB', label: 'Gibraltar' },
    { code: 'GRC', label: 'Greece' },
    { code: 'GRL', label: 'Greenland' },
    { code: 'GRD', label: 'Grenada' },
    { code: 'GLP', label: 'Guadeloupe' },
    { code: 'GUM', label: 'Guam' },
    { code: 'GTM', label: 'Guatemala' },
    { code: 'GGY', label: 'Guernsey' },
    { code: 'GIN', label: 'Guinea' },
    { code: 'GNB', label: 'Guinea-Bissau' },
    { code: 'GUY', label: 'Guyana' },
    { code: 'HTI', label: 'Haiti' },
    { code: 'HND', label: 'Honduras' },
    { code: 'HKG', label: 'Hong Kong' },
    { code: 'HUN', label: 'Hungary' },
    { code: 'ISL', label: 'Iceland' },
    { code: 'IND', label: 'India' },
    { code: 'IDN', label: 'Indonesia' },
    { code: 'IRN', label: 'Iran' },
    { code: 'IRQ', label: 'Iraq' },
    { code: 'IRL', label: 'Ireland' },
    { code: 'IMN', label: 'Isle of Man' },
    { code: 'ISR', label: 'Israel' },
    { code: 'ITA', label: 'Italy' },
    { code: 'JAM', label: 'Jamaica' },
    { code: 'JPN', label: 'Japan' },
    { code: 'JEY', label: 'Jersey' },
    { code: 'JOR', label: 'Jordan' },
    { code: 'KAZ', label: 'Kazakhstan' },
    { code: 'KEN', label: 'Kenya' },
    { code: 'KIR', label: 'Kiribati' },
    { code: 'PRK', label: 'North Korea' },
    { code: 'KOR', label: 'South Korea' },
    { code: 'KWT', label: 'Kuwait' },
    { code: 'KGZ', label: 'Kyrgyzstan' },
    { code: 'LAO', label: 'Laos' },
    { code: 'LVA', label: 'Latvia' },
    { code: 'LBN', label: 'Lebanon' },
    { code: 'LSO', label: 'Lesotho' },
    { code: 'LBR', label: 'Liberia' },
    { code: 'LBY', label: 'Libya' },
    { code: 'LIE', label: 'Liechtenstein' },
    { code: 'LTU', label: 'Lithuania' },
    { code: 'LUX', label: 'Luxembourg' },
    { code: 'MAC', label: 'Macao' },
    { code: 'MKD', label: 'North Macedonia' },
    { code: 'MDG', label: 'Madagascar' },
    { code: 'MWI', label: 'Malawi' },
    { code: 'MYS', label: 'Malaysia' },
    { code: 'MDV', label: 'Maldives' },
    { code: 'MLI', label: 'Mali' },
    { code: 'MLT', label: 'Malta' },
    { code: 'MHL', label: 'Marshall Islands' },
    { code: 'MTQ', label: 'Martinique' },
    { code: 'MRT', label: 'Mauritania' },
    { code: 'MUS', label: 'Mauritius' },
    { code: 'MYT', label: 'Mayotte' },
    { code: 'MEX', label: 'Mexico' },
    { code: 'FSM', label: 'Micronesia' },
    { code: 'MDA', label: 'Moldova' },
    { code: 'MCO', label: 'Monaco' },
    { code: 'MNG', label: 'Mongolia' },
    { code: 'MNE', label: 'Montenegro' },
    { code: 'MSR', label: 'Montserrat' },
    { code: 'MAR', label: 'Morocco' },
    { code: 'MOZ', label: 'Mozambique' },
    { code: 'MMR', label: 'Myanmar' },
    { code: 'NAM', label: 'Namibia' },
    { code: 'NRU', label: 'Nauru' },
    { code: 'NPL', label: 'Nepal' },
    { code: 'NLD', label: 'Netherlands' },
    { code: 'NCL', label: 'New Caledonia' },
    { code: 'NZL', label: 'New Zealand' },
    { code: 'NIC', label: 'Nicaragua' },
    { code: 'NER', label: 'Niger' },
    { code: 'NGA', label: 'Nigeria' },
    { code: 'NIU', label: 'Niue' },
    { code: 'NFK', label: 'Norfolk Island' },
    { code: 'MNP', label: 'Northern Mariana Islands' },
    { code: 'NOR', label: 'Norway' },
    { code: 'OMN', label: 'Oman' },
    { code: 'PAK', label: 'Pakistan' },
    { code: 'PLW', label: 'Palau' },
    { code: 'PSE', label: 'Palestine' },
    { code: 'PAN', label: 'Panama' },
    { code: 'PNG', label: 'Papua New Guinea' },
    { code: 'PRY', label: 'Paraguay' },
    { code: 'PER', label: 'Peru' },
    { code: 'PHL', label: 'Philippines' },
    { code: 'PCN', label: 'Pitcairn Islands' },
    { code: 'POL', label: 'Poland' },
    { code: 'PRT', label: 'Portugal' },
    { code: 'PRI', label: 'Puerto Rico' },
    { code: 'QAT', label: 'Qatar' },
    { code: 'REU', label: 'Réunion' },
    { code: 'ROU', label: 'Romania' },
    { code: 'RUS', label: 'Russia' },
    { code: 'RWA', label: 'Rwanda' },
    { code: 'BLM', label: 'Saint Barthélemy' },
    { code: 'SHN', label: 'Saint Helena' },
    { code: 'KNA', label: 'Saint Kitts and Nevis' },
    { code: 'LCA', label: 'Saint Lucia' },
    { code: 'MAF', label: 'Saint Martin' },
    { code: 'SPM', label: 'Saint Pierre and Miquelon' },
    { code: 'VCT', label: 'Saint Vincent and the Grenadines' },
    { code: 'WSM', label: 'Samoa' },
    { code: 'SMR', label: 'San Marino' },
    { code: 'STP', label: 'São Tomé and Príncipe' },
    { code: 'SAU', label: 'Saudi Arabia' },
    { code: 'SEN', label: 'Senegal' },
    { code: 'SRB', label: 'Serbia' },
    { code: 'SYC', label: 'Seychelles' },
    { code: 'SLE', label: 'Sierra Leone' },
    { code: 'SGP', label: 'Singapore' },
    { code: 'SXM', label: 'Sint Maarten' },
    { code: 'SVK', label: 'Slovakia' },
    { code: 'SVN', label: 'Slovenia' },
    { code: 'SLB', label: 'Solomon Islands' },
    { code: 'SOM', label: 'Somalia' },
    { code: 'ZAF', label: 'South Africa' },
    { code: 'SSD', label: 'South Sudan' },
    { code: 'ESP', label: 'Spain' },
    { code: 'LKA', label: 'Sri Lanka' },
    { code: 'SDN', label: 'Sudan' },
    { code: 'SUR', label: 'Suriname' },
    { code: 'SWE', label: 'Sweden' },
    { code: 'CHE', label: 'Switzerland' },
    { code: 'SYR', label: 'Syria' },
    { code: 'TWN', label: 'Taiwan' },
    { code: 'TJK', label: 'Tajikistan' },
    { code: 'TZA', label: 'Tanzania' },
    { code: 'THA', label: 'Thailand' },
    { code: 'TLS', label: 'Timor-Leste' },
    { code: 'TGO', label: 'Togo' },
    { code: 'TKL', label: 'Tokelau' },
    { code: 'TON', label: 'Tonga' },
    { code: 'TTO', label: 'Trinidad and Tobago' },
    { code: 'TUN', label: 'Tunisia' },
    { code: 'TUR', label: 'Turkey' },
    { code: 'TKM', label: 'Turkmenistan' },
    { code: 'TCA', label: 'Turks and Caicos Islands' },
    { code: 'TUV', label: 'Tuvalu' },
    { code: 'UGA', label: 'Uganda' },
    { code: 'UKR', label: 'Ukraine' },
    { code: 'ARE', label: 'United Arab Emirates' },
    { code: 'GBR', label: 'United Kingdom' },
    { code: 'USA', label: 'United States' },
    { code: 'URY', label: 'Uruguay' },
    { code: 'UZB', label: 'Uzbekistan' },
    { code: 'VUT', label: 'Vanuatu' },
    { code: 'VEN', label: 'Venezuela' },
    { code: 'VNM', label: 'Vietnam' },
    { code: 'VIR', label: 'Virgin Islands, U.S.' },
    { code: 'WLF', label: 'Wallis and Futuna' },
    { code: 'ESH', label: 'Western Sahara' },
    { code: 'YEM', label: 'Yemen' },
    { code: 'ZMB', label: 'Zambia' },
    { code: 'ZWE', label: 'Zimbabwe' }
];